### ISSUE TITLE
[Errno 2] No such file or directory: 'all_data/ut-zap50k//metadata_compositional-split-natural.t7'

### ISSUE THREAD

**Issue by alice-cool** [zhaohengz/CAILA#2]
Traceback (most recent call last):
  File "utils/reorganize_utzap.py", line 25, in <module>
    data = torch.load(root+'/metadata_compositional-split-natural.t7')

**Comment by zhaohengz** [comment]
Hi,

Can you paste your file directory here for me, please?

**Comment by alice-cool** [comment]
![image](https://github.com/zhaohengz/CAILA/assets/16870890/0f800a64-90f0-4635-ac80-8eb279f6b78e)
你好，上面是我的datasetss 目录下，当时这个目录下只有红框的5个压缩文件，我是手动下载到这个目录里。因为老是显示网络connection 问题，所以手动下载，所以在downloaddata.bash 中我屏蔽了下载语句
![image](https://github.com/zhaohengz/CAILA/assets/16870890/71ffb850-a774-4937-9b0b-967806366b77)运行的是这个bash ./utils/download_data.sh  /group_file/HUyongli/byd/CAILA-release/datasetss/ 对5个压缩包进行处理，结果就是在datasetss 中生成了这么多文件夹和内容
![image](https://github.com/zhaohengz/CAILA/assets/16870890/9964cbdc-7ad6-46c9-87a6-f9b4a36de89a)
但是运行了一段时间后就开始报错
![image](https://github.com/zhaohengz/CAILA/assets/16870890/ac42f78e-b694-46f6-a1d5-1e74266b3129)
辛苦您了。

**Comment by zhaohengz** [comment]
Hi, it seems that the original website is no longer hosting the file.

Please find the splits here: [link](https://drive.google.com/file/d/1q7G7yYAvCE9j9fWVGpEwJwtJjOVL97Xf/view?usp=sharing) and untar them to the corresponding folder.

-----------------

你好，请将[link](https://drive.google.com/file/d/1q7G7yYAvCE9j9fWVGpEwJwtJjOVL97Xf/view?usp=sharing)里的文件解压到对应文件夹。

**Comment by alice-cool** [comment]
谢谢您的及时回复，我试试，谢谢



---Original---
From: "Zhaoheng ***@***.***&gt;
Date: Thu, Jan 18, 2024 12:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhaohengz/CAILA] [Errno 2] No such file or directory:'all_data/ut-zap50k//metadata_compositional-split-natural.t7' (Issue #2)




 
Hi, it seems that the original website is no longer hosting the file.
 
Please find the splits here: link and untar them to the corresponding folder.
 
 
你好，请将link里的文件解压到对应文件夹。
